import type { CustomerMenuData, OrderTicket, TableSummary } from "@/lib/types";

const photos = {
  salmon:
    "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=900&q=85",
  beef: "https://images.unsplash.com/photo-1515668236457-83c3b8764839?auto=format&fit=crop&w=900&q=85",
  salad:
    "https://images.unsplash.com/photo-1588791167871-c1dc0ff28edd?auto=format&fit=crop&w=900&q=85",
  noodles:
    "https://images.unsplash.com/photo-1581691762074-a12a9799107e?auto=format&fit=crop&w=900&q=85",
  dessert:
    "https://images.unsplash.com/photo-1590741664176-7fbd7e2592a0?auto=format&fit=crop&w=900&q=85",
  drink:
    "https://images.unsplash.com/photo-1665989099287-3948d871232c?auto=format&fit=crop&w=900&q=85",
};

export const demoMenu: CustomerMenuData = {
  restaurant: { id: "demo", name: "SAVOUR", logoUrl: null },
  session: {
    id: "demo-session",
    tableName: "A05",
    status: "OPEN",
    billRequested: false,
  },
  settings: {
    allowNotes: true,
    enableStaffCall: true,
    enableBillRequest: true,
  },
  categories: [
    { id: "recommended", name: "แนะนำ", sortOrder: 0 },
    { id: "main", name: "อาหารจานเดียว", sortOrder: 1 },
    { id: "meat", name: "เนื้อ", sortOrder: 2 },
    { id: "seafood", name: "ทะเล", sortOrder: 3 },
    { id: "vegetable", name: "ผัก", sortOrder: 4 },
    { id: "drink", name: "เครื่องดื่ม", sortOrder: 5 },
    { id: "dessert", name: "ของหวาน", sortOrder: 6 },
  ],
  items: [
    {
      id: "salmon",
      categoryId: "seafood",
      name: "แซลมอนย่างซอสยูซุ",
      description: "แซลมอนย่างซอสยูซุหอมสดชื่น",
      priceSatang: 32000,
      imageUrl: photos.salmon,
      recommended: true,
      available: true,
      trackStock: true,
      soldOut: false,
      stockQuantity: 8,
      lowStockThreshold: 5,
      modifierGroups: [],
    },
    {
      id: "wagyu",
      categoryId: "meat",
      name: "เนื้อย่างวากิว",
      description: "เนื้อวากิวย่างถ่าน เลือกระดับความสุกได้",
      priceSatang: 45000,
      imageUrl: photos.beef,
      recommended: true,
      available: true,
      trackStock: true,
      soldOut: false,
      stockQuantity: 12,
      lowStockThreshold: 4,
      modifierGroups: [
        {
          id: "doneness",
          name: "ระดับความสุก",
          required: true,
          minSelections: 1,
          maxSelections: 1,
          options: [
            { id: "medium-rare", name: "Medium rare", priceDeltaSatang: 0 },
            { id: "medium", name: "Medium", priceDeltaSatang: 0 },
            { id: "well-done", name: "Well done", priceDeltaSatang: 0 },
          ],
        },
      ],
    },
    {
      id: "salad",
      categoryId: "vegetable",
      name: "สลัดผักย่าง",
      description: "ผักตามฤดูกาลย่าง เสิร์ฟกับน้ำสลัดงา",
      priceSatang: 19000,
      imageUrl: photos.salad,
      recommended: true,
      available: true,
      trackStock: false,
      soldOut: false,
      stockQuantity: null,
      lowStockThreshold: null,
      modifierGroups: [],
    },
    {
      id: "ramen",
      categoryId: "main",
      name: "ราเมนซีฟู้ด",
      description: "ราเมนซีฟู้ดน้ำซุปรสเข้มข้น",
      priceSatang: 28000,
      imageUrl: photos.noodles,
      recommended: false,
      available: true,
      trackStock: true,
      soldOut: false,
      stockQuantity: 3,
      lowStockThreshold: 5,
      modifierGroups: [],
    },
    {
      id: "dessert",
      categoryId: "dessert",
      name: "ช็อกโกแลตเบอร์รี่",
      description: "ดาร์กช็อกโกแลตและเบอร์รี่สด",
      priceSatang: 18000,
      imageUrl: photos.dessert,
      recommended: false,
      available: true,
      trackStock: false,
      soldOut: false,
      stockQuantity: null,
      lowStockThreshold: null,
      modifierGroups: [],
    },
    {
      id: "ruby",
      categoryId: "drink",
      name: "Ruby Citrus",
      description: "ซิตรัสและเบอร์รี่โทนิก",
      priceSatang: 15000,
      imageUrl: photos.drink,
      recommended: false,
      available: true,
      trackStock: true,
      soldOut: true,
      stockQuantity: 0,
      lowStockThreshold: 4,
      modifierGroups: [],
    },
  ],
};

export const demoTables: TableSummary[] = [
  {
    id: "a01",
    name: "A01",
    seats: 4,
    zoneId: "a",
    zoneName: "Main Dining",
    state: "AVAILABLE",
    sessionId: null,
    openedAt: null,
    guestCount: null,
    totalSatang: 0,
    attentionCount: 0,
    latestItems: [],
  },
  {
    id: "a02",
    name: "A02",
    seats: 2,
    zoneId: "a",
    zoneName: "Main Dining",
    state: "NEW_ORDER",
    sessionId: "s02",
    openedAt: new Date(Date.now() - 4 * 60_000).toISOString(),
    guestCount: 2,
    totalSatang: 124000,
    attentionCount: 1,
    latestItems: ["เนื้อย่างวากิว ×2", "สลัดผักย่าง ×1", "+3 รายการ"],
  },
  {
    id: "a03",
    name: "A03",
    seats: 4,
    zoneId: "a",
    zoneName: "Main Dining",
    state: "ACTIVE",
    sessionId: "s03",
    openedAt: new Date(Date.now() - 29 * 60_000).toISOString(),
    guestCount: 3,
    totalSatang: 98000,
    attentionCount: 0,
    latestItems: ["แซลมอนย่าง ×1", "Ruby Citrus ×2"],
  },
  {
    id: "a04",
    name: "A04",
    seats: 6,
    zoneId: "a",
    zoneName: "Main Dining",
    state: "CALLING_STAFF",
    sessionId: "s04",
    openedAt: new Date(Date.now() - 42 * 60_000).toISOString(),
    guestCount: 5,
    totalSatang: 284000,
    attentionCount: 1,
    latestItems: ["เรียกพนักงาน"],
  },
  {
    id: "a05",
    name: "A05",
    seats: 4,
    zoneId: "a",
    zoneName: "Main Dining",
    state: "READY",
    sessionId: "s05",
    openedAt: new Date(Date.now() - 18 * 60_000).toISOString(),
    guestCount: 3,
    totalSatang: 77000,
    attentionCount: 2,
    latestItems: ["อาหารพร้อมเสิร์ฟ", "ราเมนซีฟู้ด ×2"],
  },
  {
    id: "a06",
    name: "A06",
    seats: 2,
    zoneId: "a",
    zoneName: "Main Dining",
    state: "REQUEST_BILL",
    sessionId: "s06",
    openedAt: new Date(Date.now() - 53 * 60_000).toISOString(),
    guestCount: 2,
    totalSatang: 156000,
    attentionCount: 1,
    latestItems: ["ขอเช็กบิล"],
  },
  {
    id: "a07",
    name: "A07",
    seats: 4,
    zoneId: "a",
    zoneName: "Main Dining",
    state: "PREPARING",
    sessionId: "s07",
    openedAt: new Date(Date.now() - 10 * 60_000).toISOString(),
    guestCount: 4,
    totalSatang: 62000,
    attentionCount: 0,
    latestItems: ["กำลังเตรียม 2 รายการ"],
  },
  {
    id: "a08",
    name: "A08",
    seats: 8,
    zoneId: "a",
    zoneName: "Main Dining",
    state: "AVAILABLE",
    sessionId: null,
    openedAt: null,
    guestCount: null,
    totalSatang: 0,
    attentionCount: 0,
    latestItems: [],
  },
];

export const demoOrders: OrderTicket[] = [
  {
    id: "o1048",
    number: 1048,
    tableName: "A02",
    status: "NEW",
    createdAt: new Date(Date.now() - 3 * 60_000).toISOString(),
    note: "เนื้อ Medium rare · ไม่ใส่หอม",
    items: [
      { name: "เนื้อย่างวากิว", quantity: 2, note: "Medium rare" },
      { name: "สลัดผักย่าง", quantity: 1, note: null },
      { name: "Ruby Citrus", quantity: 2, note: null },
    ],
  },
  {
    id: "o1047",
    number: 1047,
    tableName: "A07",
    status: "PREPARING",
    createdAt: new Date(Date.now() - 11 * 60_000).toISOString(),
    note: null,
    items: [
      { name: "แซลมอนย่างซอสยูซุ", quantity: 1, note: null },
      { name: "ราเมนซีฟู้ด", quantity: 1, note: "ไม่ใส่ต้นหอม" },
    ],
  },
  {
    id: "o1046",
    number: 1046,
    tableName: "A05",
    status: "READY",
    createdAt: new Date(Date.now() - 18 * 60_000).toISOString(),
    note: null,
    items: [{ name: "ราเมนซีฟู้ด", quantity: 2, note: null }],
  },
];
